/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author shemeneroje
 */
public class QuizGUI extends javax.swing.JFrame {
    private final ArrayList<Options> questions;
    private int index = 0, correct = 0;
    private final ButtonGroup bg = new ButtonGroup();

    public QuizGUI() {
        initComponents();
        // Create an instance of Questions to fetch all questions
        Questions q = new Questions(); 

        //get Fetch questions from Questions
        questions = q.getQuestions();
        System.out.println("HEllo");

        // Add radio buttons to the button group
        bg.add(opt1);
        bg.add(opt2);
        bg.add(opt3);
        bg.add(opt4);

        // Set up action listener for Next button
        nextQuestion.addActionListener(evt -> nextQuestionActionPerformed());

        // Display the first question
        displayQuestion();
    }

    // Display the current question
    public void displayQuestion() {
        if (index < questions.size()) {
            Options currentQuestion = questions.get(index);
            Ouestion.setText(currentQuestion.getQuestionText());
            opt1.setText(currentQuestion.getOptions().get(0));
            opt2.setText(currentQuestion.getOptions().get(1));
            opt3.setText(currentQuestion.getOptions().get(2));
            opt4.setText(currentQuestion.getOptions().get(3));

            bg.clearSelection();
            enableRbuttons(true);
        }
    }

    // Check the selected option
    public void getSelectedOption() {
        JRadioButton selectedButton = null;
        if (opt1.isSelected()) selectedButton = opt1;
        else if (opt2.isSelected()) selectedButton = opt2;
        else if (opt3.isSelected()) selectedButton = opt3;
        else if (opt4.isSelected()) selectedButton = opt4;

        if (selectedButton != null && selectedButton.getText().equals(questions.get(index).getCorrectAnswer())) {
            correct++;
        }
    }

    // Enable or disable radio buttons
    public void enableRbuttons(boolean enable) {
        opt1.setEnabled(enable);
        opt2.setEnabled(enable);
        opt3.setEnabled(enable);
        opt4.setEnabled(enable);
    }

    // Handle "Next" button click
    private void nextQuestionActionPerformed() {
        if (nextQuestion.getText().equals("Play Again")) {
            resetQuiz();
        } else if (index >= questions.size()) {
            Ouestion.setText("Quiz Completed! Your Score: " + correct + " / " + questions.size());
            enableRbuttons(false);
            nextQuestion.setText("Play Again");
        } else {
            getSelectedOption();
            index++;
            displayQuestion();
            if (index == questions.size() - 1) {
                nextQuestion.setText("Finish and See The Result");
            } else {
                nextQuestion.setText("Next");
            }
        }
    }

    // Reset the quiz
    private void resetQuiz() {
        index = 0;
        correct = 0;
        displayQuestion();
        nextQuestion.setText("Next");
        enableRbuttons(true);
    }

   
    
    
                         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OuestionContainer = new javax.swing.JPanel();
        Ouestion = new javax.swing.JLabel();
        menu_btn = new javax.swing.JButton();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        nextQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        OuestionContainer.setBackground(new java.awt.Color(0, 255, 204));

        Ouestion.setFont(new java.awt.Font("Chalkduster", 1, 18)); // NOI18N
        Ouestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ouestion.setText("Ouestion here ??");

        menu_btn.setBackground(new java.awt.Color(204, 255, 204));
        menu_btn.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        menu_btn.setText("Menu");
        menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OuestionContainerLayout = new javax.swing.GroupLayout(OuestionContainer);
        OuestionContainer.setLayout(OuestionContainerLayout);
        OuestionContainerLayout.setHorizontalGroup(
            OuestionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuestionContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ouestion, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(OuestionContainerLayout.createSequentialGroup()
                .addComponent(menu_btn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OuestionContainerLayout.setVerticalGroup(
            OuestionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuestionContainerLayout.createSequentialGroup()
                .addComponent(menu_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ouestion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        opt1.setBackground(new java.awt.Color(204, 255, 204));
        opt1.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        opt1.setText("Option 1 ");

        opt2.setBackground(new java.awt.Color(204, 255, 204));
        opt2.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        opt2.setText("Option 2");

        opt4.setBackground(new java.awt.Color(204, 255, 204));
        opt4.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        opt4.setText("Option 4");

        opt3.setBackground(new java.awt.Color(204, 255, 204));
        opt3.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        opt3.setText("Option 3");

        nextQuestion.setBackground(new java.awt.Color(0, 255, 204));
        nextQuestion.setFont(new java.awt.Font("Chalkduster", 0, 16)); // NOI18N
        nextQuestion.setText("Next");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt4, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                            .addComponent(opt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(nextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OuestionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OuestionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(opt1)
                .addGap(4, 4, 4)
                .addComponent(opt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(nextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_btnActionPerformed
        // TODO add your handling code here:
        Menu2GUI myGUI = new Menu2GUI(); 
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_btnActionPerformed
    
    

   
    
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuizGUI().setVisible(true);
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ouestion;
    private javax.swing.JPanel OuestionContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu_btn;
    private javax.swing.JButton nextQuestion;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    // End of variables declaration//GEN-END:variables
}
